# Generated by Django 4.2 on 2024-03-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_exercise_workoutplans_alter_exercise_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='workoutplans',
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='exercises',
            field=models.ManyToManyField(to='admin_app.exercise'),
        ),
    ]
