# Generated by Django 4.2 on 2024-07-20 19:07

from django.db import migrations, models
import gym_app.admin_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0005_alter_workoutplan_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="target_area",
            field=models.CharField(
                choices=[
                    ("CHEST", "Chest"),
                    ("LEGS", "Legs"),
                    ("BICEPS", "Biceps"),
                    ("TRICEPS", "Triceps"),
                    ("SHOULDERS", "Shoulders"),
                    ("BACK", "Back"),
                ],
                max_length=50,
                validators=[gym_app.admin_app.validators.validate_exercise_target_area],
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="exercises",
            field=models.ManyToManyField(
                related_name="exercises", to="admin_app.exercise"
            ),
        ),
        migrations.AlterField(
            model_name="workoutplan",
            name="workout_type",
            field=models.CharField(
                choices=[
                    ("CARDIO", "Cardio"),
                    ("HIIT", "HIIT"),
                    ("LIIT", "LIIT"),
                    ("OTHER", "Other"),
                    ("STRENGTH", "Strength"),
                    ("HYPERTROPHY", "Hypertrophy"),
                ],
                max_length=50,
                validators=[
                    gym_app.admin_app.validators.validate_workout_plan_workouttype
                ],
            ),
        ),
    ]
