# Generated by Django 4.2 on 2024-07-27 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0009_alter_exercise_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={},
        ),
    ]
