# Generated by Django 4.2 on 2024-09-18 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_app", "0011_alter_exercise_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="exercise",
            options={
                "permissions": [
                    (
                        "readonly_exercises",
                        "can view exercise but not add, change or delete.",
                    )
                ]
            },
        ),
    ]
