name: Deploy Docker Compose to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Set up SSH Agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_KEY }}

    - name: Deploy on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
          cd /home/${{ secrets.EC2_USER }}/app || mkdir -p /home/${{ secrets.EC2_USER }}/app && cd /home/${{ secrets.EC2_USER }}/app
          if [ ! -d .git ]; then
            git clone https://github.com/JussGabz/GymApp-2.0.git .
          else
            git reset --hard
            git pull origin main
          fi
          docker-compose down
          docker-compose up -d --build
        EOF
