name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH agent and add the private key
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Connect to EC2 and pull changes
    - name: Deploy to EC2 Instance
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << EOF
          cd /home/ec2-user/GymApp-2.0
          git pull origin main

          # Ensure the environment variables file exists
          if [ ! -f .env ]; then
            echo "Environment file not found! Exiting."
            exit 1
          fi

          # Use docker-compose to pull, build, and restart the app
          docker-compose down
          docker-compose pull
          docker-compose up -d --build
        EOF
