name: Deploy to EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up SSH agent and add the private key
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    # Build the Docker image
    - name: Build Docker Image
      run: |
        docker build -t .

    # Deploy to EC2
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
        docker stop my-docker-app || true
        docker rm my-docker-app || true
        docker pull my-docker-app:latest
        docker run -d -p 80:80 --name my-docker-app my-docker-app:latest
        EOF
